use std::collections::HashSet;
use std::fs;

#[derive(Clone, Debug)]
pub(crate) struct AltSvcCache {
    pub enabled: bool,
    pub path: Option<String>,
    pub ctrl_bits: i64,
    entries: Vec<String>,
    loaded_paths: HashSet<String>,
}

impl Default for AltSvcCache {
    fn default() -> Self {
        Self {
            enabled: false,
            path: None,
            ctrl_bits: 0,
            entries: Vec::new(),
            loaded_paths: HashSet::new(),
        }
    }
}

impl AltSvcCache {
    pub(crate) fn clear_runtime(&mut self) {
        // Alt-Svc is connection state that persists across easy-handle transfers.
    }

    pub(crate) fn remember_raw(&mut self, line: &str) {
        let value = line.trim();
        if value.eq_ignore_ascii_case("clear;") {
            self.entries.clear();
            return;
        }
        if !self.entries.iter().any(|entry| entry == value) {
            self.entries.push(value.to_string());
        }
    }

    pub(crate) fn remember_header(&mut self, authority_host: &str, value: &str) {
        let trimmed = value.trim();
        if trimmed.eq_ignore_ascii_case("clear;") {
            self.entries.clear();
            return;
        }
        for part in trimmed.split(',') {
            let part = part.trim();
            let Some((proto, alt_value)) = part.split_once('=') else {
                continue;
            };
            let alt_value = alt_value.trim().trim_matches('"');
            let normalized = if alt_value.starts_with(':') {
                format!("{}=\"{}{alt_value}\"", proto.trim(), authority_host)
            } else {
                format!("{}=\"{}\"", proto.trim(), alt_value)
            };
            self.remember_raw(&normalized);
        }
    }

    pub(crate) fn load_from_path(&mut self, path: &str) -> std::io::Result<()> {
        if path.trim().is_empty() || !self.loaded_paths.insert(path.to_string()) {
            return Ok(());
        }
        let text = match fs::read_to_string(path) {
            Ok(text) => text,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
            Err(error) => return Err(error),
        };
        for line in text.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            self.remember_raw(trimmed);
        }
        Ok(())
    }

    pub(crate) fn flush_to_path(&self, path: &str) -> std::io::Result<()> {
        let mut out = String::from(
            "# Your alt-svc cache. https://curl.se/docs/alt-svc.html\n# This file was generated by libcurl! Edit at your own risk.\n",
        );
        for entry in &self.entries {
            out.push_str(entry);
            out.push('\n');
        }
        fs::write(path, out)
    }

    pub(crate) fn entries(&self) -> &[String] {
        &self.entries
    }
}
