use crate::http::request::Origin;
use crate::http::response::split_header_line;
use std::fs;

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct Cookie {
    pub name: String,
    pub value: String,
    pub domain: String,
    pub path: String,
    pub secure: bool,
    pub host_only: bool,
}

#[derive(Clone, Debug, Default)]
pub(crate) struct CookieStore {
    cookies: Vec<Cookie>,
}

impl CookieStore {
    pub(crate) fn apply_request(&self, url: &str, manual_cookie: Option<&str>) -> Option<String> {
        if let Some(cookie) = manual_cookie.filter(|value| !value.trim().is_empty()) {
            return Some(cookie.to_string());
        }
        let origin = Origin::from_url(url)?;
        let path = path_for_url(url);
        let matched = self
            .cookies
            .iter()
            .filter(|cookie| cookie_matches(cookie, &origin.host, &path, origin.scheme == "https"))
            .map(|cookie| format!("{}={}", cookie.name, cookie.value))
            .collect::<Vec<_>>();
        (!matched.is_empty()).then(|| matched.join("; "))
    }

    pub(crate) fn store_set_cookie(&mut self, url: &str, header_value: &str) {
        let Some(origin) = Origin::from_url(url) else {
            return;
        };
        let Some(cookie) = parse_set_cookie(&origin.host, &path_for_url(url), header_value) else {
            return;
        };
        self.cookies.retain(|existing| {
            !(existing.name == cookie.name
                && existing.domain.eq_ignore_ascii_case(&cookie.domain)
                && existing.path == cookie.path)
        });
        self.cookies.push(cookie);
    }

    pub(crate) fn flush_to_path(&self, path: &str) -> std::io::Result<()> {
        fs::write(path, self.serialize_netscape())
    }

    pub(crate) fn serialize_netscape(&self) -> String {
        let lines = self
            .cookies
            .iter()
            .rev()
            .map(|cookie| {
                format!(
                    "{}\t{}\t{}\t{}\t0\t{}\t{}",
                    cookie.domain,
                    if cookie.host_only { "FALSE" } else { "TRUE" },
                    cookie.path,
                    if cookie.secure { "TRUE" } else { "FALSE" },
                    cookie.name,
                    cookie.value
                )
            })
            .collect::<Vec<_>>();
        render_netscape_lines(&lines)
    }
}

pub(crate) fn render_netscape_lines(lines: &[String]) -> String {
    let mut out = String::from(
        "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n",
    );
    for line in lines {
        out.push_str(line);
        out.push('\n');
    }
    out
}

pub(crate) fn parse_set_cookie(
    host: &str,
    request_path: &str,
    header_value: &str,
) -> Option<Cookie> {
    let mut segments = header_value.split(';');
    let (name, value) = segments.next()?.split_once('=')?;
    if has_control(name) || has_control(value) {
        return None;
    }

    let mut cookie = Cookie {
        name: name.trim().to_string(),
        value: value.trim().to_string(),
        domain: host.to_ascii_lowercase(),
        path: default_cookie_path(request_path),
        secure: false,
        host_only: true,
    };

    for segment in segments {
        let trimmed = segment.trim();
        let lower = trimmed.to_ascii_lowercase();
        if lower == "secure" {
            cookie.secure = true;
            continue;
        }
        let Some((attr_name, attr_value)) = trimmed.split_once('=') else {
            continue;
        };
        match attr_name.trim().to_ascii_lowercase().as_str() {
            "domain" => {
                let candidate = attr_value
                    .trim()
                    .trim_start_matches('.')
                    .trim_end_matches('.');
                if candidate.is_empty()
                    || is_public_suffix(candidate)
                    || !domain_match(host, candidate)
                {
                    return None;
                }
                cookie.domain = candidate.to_ascii_lowercase();
                cookie.host_only = false;
            }
            "path" => {
                if !attr_value.trim().is_empty() {
                    cookie.path = attr_value.trim().to_string();
                }
            }
            _ => {}
        }
    }

    Some(cookie)
}

pub(crate) fn record_from_header(store: &mut CookieStore, url: &str, line: &str) {
    if let Some((name, value)) = split_header_line(line) {
        if name.eq_ignore_ascii_case("set-cookie") {
            store.store_set_cookie(url, value);
        }
    }
}

fn cookie_matches(cookie: &Cookie, host: &str, path: &str, secure_request: bool) -> bool {
    if cookie.secure && !secure_request {
        return false;
    }
    if cookie.host_only {
        if !host.eq_ignore_ascii_case(&cookie.domain) {
            return false;
        }
    } else if !domain_match(host, &cookie.domain) {
        return false;
    }
    path.starts_with(&cookie.path)
}

fn path_for_url(url: &str) -> String {
    let Some((_, rest)) = url.split_once("://") else {
        return "/".to_string();
    };
    let trimmed = rest.split('#').next().unwrap_or(rest);
    let path_start = trimmed.find('/').unwrap_or(trimmed.len());
    let suffix = &trimmed[path_start..];
    if suffix.is_empty() {
        "/".to_string()
    } else {
        suffix.split('?').next().unwrap_or("/").to_string()
    }
}

fn default_cookie_path(request_path: &str) -> String {
    if !request_path.starts_with('/') {
        return "/".to_string();
    }
    let last_slash = request_path.rfind('/').unwrap_or(0);
    if last_slash == 0 {
        "/".to_string()
    } else {
        request_path[..=last_slash].to_string()
    }
}

fn domain_match(host: &str, domain: &str) -> bool {
    host.eq_ignore_ascii_case(domain)
        || host
            .to_ascii_lowercase()
            .strip_suffix(&format!(".{}", domain.to_ascii_lowercase()))
            .is_some()
}

fn is_public_suffix(domain: &str) -> bool {
    let domain = domain.to_ascii_lowercase();
    if !domain.contains('.') {
        return true;
    }
    matches!(
        domain.as_str(),
        "com" | "net" | "org" | "edu" | "gov" | "co.uk" | "uk"
    )
}

fn has_control(value: &str) -> bool {
    value.bytes().any(|byte| byte < 0x20 || byte == 0x7f)
}

#[cfg(test)]
mod tests {
    use super::{parse_set_cookie, CookieStore};

    #[test]
    fn cookie_rejects_public_suffix_domains() {
        let cookie = parse_set_cookie("curl.co.uk", "/index", "a=b; Domain=co.uk");
        assert!(cookie.is_none());
    }

    #[test]
    fn cookie_rejects_control_characters() {
        let cookie = parse_set_cookie("example.test", "/index", "a=\x01b");
        assert!(cookie.is_none());
    }

    #[test]
    fn cookie_store_only_emits_matching_domain() {
        let mut store = CookieStore::default();
        store.store_set_cookie("http://example.test/path", "sid=one; Path=/");
        let header = store
            .apply_request("http://example.test/next", None)
            .expect("cookie header");
        assert_eq!(header, "sid=one");
        assert!(store
            .apply_request("http://other.test/next", None)
            .is_none());
    }

    #[test]
    fn cookie_jar_serialization_matches_netscape_layout() {
        let mut store = CookieStore::default();
        store.store_set_cookie("http://127.0.0.1/we/want/1905", "foobar=name;");
        store.store_set_cookie("http://127.0.0.1/we/want/1905", "secondcookie=present;");
        assert_eq!(
            store.serialize_netscape(),
            "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n127.0.0.1\tFALSE\t/we/want/\tFALSE\t0\tsecondcookie\tpresent\n127.0.0.1\tFALSE\t/we/want/\tFALSE\t0\tfoobar\tname\n"
        );
    }
}
