use crate::http::response::split_header_line;
use std::collections::HashSet;
use std::fs;
use std::net::IpAddr;
use std::time::{SystemTime, UNIX_EPOCH};

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct HstsEntry {
    pub host: String,
    pub include_subdomains: bool,
    pub expires: i64,
    pub expire_text: Option<String>,
}

#[derive(Clone, Debug)]
pub(crate) struct HstsStore {
    entries: Vec<HstsEntry>,
    loaded_paths: HashSet<String>,
}

impl Default for HstsStore {
    fn default() -> Self {
        Self {
            entries: Vec::new(),
            loaded_paths: HashSet::new(),
        }
    }
}

impl HstsStore {
    pub(crate) fn remember(&mut self, host: &str, include_subdomains: bool, expires: i64) {
        self.remember_absolute(host, include_subdomains, expires, None);
    }

    pub(crate) fn remember_absolute(
        &mut self,
        host: &str,
        include_subdomains: bool,
        expires: i64,
        expire_text: Option<String>,
    ) {
        let Some(host) = normalize_host(host) else {
            return;
        };
        if expires <= current_unix_time() {
            self.remove_exact(&host);
            return;
        }
        self.remove_exact(&host);
        self.entries.push(HstsEntry {
            host,
            include_subdomains,
            expires,
            expire_text,
        });
    }

    pub(crate) fn remember_callback_entry(
        &mut self,
        host: &str,
        include_subdomains: bool,
        expire_text: &str,
    ) {
        let Some(host) = normalize_host(host) else {
            return;
        };
        self.remove_exact(&host);
        let expires = parse_hsts_file_date(expire_text).unwrap_or(i64::MAX);
        self.entries.push(HstsEntry {
            host,
            include_subdomains,
            expires,
            expire_text: (!expire_text.is_empty()).then(|| expire_text.to_string()),
        });
    }

    pub(crate) fn lookup(&self, host: &str) -> Option<&HstsEntry> {
        let host = normalize_host(host)?;
        if is_ip_address(&host) {
            return None;
        }
        let now = current_unix_time();
        if let Some(exact) = self
            .entries
            .iter()
            .find(|entry| entry.host == host && entry.expires > now)
        {
            return Some(exact);
        }

        self.entries
            .iter()
            .filter(|entry| {
                entry.expires > now
                    && entry.include_subdomains
                    && host.len() > entry.host.len()
                    && host.ends_with(&entry.host)
                    && host.as_bytes()[host.len() - entry.host.len() - 1] == b'.'
            })
            .max_by_key(|entry| entry.host.len())
    }

    pub(crate) fn entries(&self) -> &[HstsEntry] {
        &self.entries
    }

    pub(crate) fn load_from_path(&mut self, path: &str) -> std::io::Result<()> {
        if path.trim().is_empty() || !self.loaded_paths.insert(path.to_string()) {
            return Ok(());
        }
        let text = match fs::read_to_string(path) {
            Ok(text) => text,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
            Err(error) => return Err(error),
        };
        for line in text.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            let Some((host, include_subdomains, expires, expire_text)) = parse_hsts_line(trimmed)
            else {
                continue;
            };
            self.remember_absolute(&host, include_subdomains, expires, Some(expire_text));
        }
        Ok(())
    }

    pub(crate) fn flush_to_path(&self, path: &str) -> std::io::Result<()> {
        let mut out = String::from(
            "# Your HSTS cache. https://curl.se/docs/hsts.html\n# This file was generated by libcurl! Edit at your own risk.\n",
        );
        for entry in self
            .entries
            .iter()
            .filter(|entry| entry.expires > current_unix_time())
        {
            if entry.include_subdomains {
                out.push('.');
            }
            out.push_str(&entry.host);
            out.push(' ');
            out.push('"');
            if let Some(expire_text) = entry.expire_text.as_deref() {
                out.push_str(expire_text);
            } else if entry.expires == i64::MAX {
                out.push_str("unlimited");
            } else {
                out.push_str(&format_hsts_date(entry.expires));
            }
            out.push_str("\"\n");
        }
        fs::write(path, out)
    }

    fn remove_exact(&mut self, host: &str) {
        self.entries.retain(|entry| entry.host != host);
    }
}

pub(crate) fn record_from_header(store: &mut HstsStore, url_host: &str, line: &str) {
    let Some((name, value)) = split_header_line(line) else {
        return;
    };
    if !name.eq_ignore_ascii_case("strict-transport-security") {
        return;
    }
    let Some(host) = normalize_host(url_host) else {
        return;
    };
    if is_ip_address(&host) {
        return;
    }

    let mut max_age = None;
    let mut include_subdomains = false;
    for segment in value.split(';') {
        let trimmed = segment.trim();
        if trimmed.eq_ignore_ascii_case("includesubdomains") {
            include_subdomains = true;
            continue;
        }
        let Some((attr_name, attr_value)) = trimmed.split_once('=') else {
            continue;
        };
        if attr_name.trim().eq_ignore_ascii_case("max-age") {
            max_age = attr_value.trim().parse::<i64>().ok();
        }
    }

    if let Some(max_age) = max_age {
        if max_age <= 0 {
            store.remove_exact(&host);
            return;
        }
        store.remember_absolute(
            &host,
            include_subdomains,
            current_unix_time().saturating_add(max_age),
            None,
        );
    }
}

fn parse_hsts_line(line: &str) -> Option<(String, bool, i64, String)> {
    let (host, rest) = line.split_once(' ')?;
    let expire_text = rest.trim().trim_matches('"').to_string();
    let include_subdomains = host.starts_with('.');
    let host = normalize_host(host.trim_start_matches('.'))?;
    let expires = parse_hsts_file_date(&expire_text)?;
    Some((host, include_subdomains, expires, expire_text))
}

fn normalize_host(host: &str) -> Option<String> {
    let host = host.trim().trim_end_matches('.');
    (!host.is_empty()).then(|| host.to_ascii_lowercase())
}

fn is_ip_address(host: &str) -> bool {
    host.parse::<IpAddr>().is_ok()
}

fn parse_hsts_file_date(value: &str) -> Option<i64> {
    if value.eq_ignore_ascii_case("unlimited") {
        return Some(i64::MAX);
    }
    let (date, time) = value.split_once(' ')?;
    if date.len() != 8 {
        return None;
    }
    let year = date[0..4].parse::<i32>().ok()?;
    let month = date[4..6].parse::<u32>().ok()?;
    let day = date[6..8].parse::<u32>().ok()?;
    let mut time_parts = time.split(':');
    let hour = time_parts.next()?.parse::<u32>().ok()?;
    let minute = time_parts.next()?.parse::<u32>().ok()?;
    let second = time_parts.next()?.parse::<u32>().ok()?;
    Some(unix_timestamp_utc(year, month, day, hour, minute, second))
}

fn format_hsts_date(timestamp: i64) -> String {
    let days = timestamp.div_euclid(86_400);
    let seconds = timestamp.rem_euclid(86_400);
    let (year, month, day) = civil_from_days(days);
    let hour = seconds / 3_600;
    let minute = (seconds % 3_600) / 60;
    let second = seconds % 60;
    format!("{year:04}{month:02}{day:02} {hour:02}:{minute:02}:{second:02}")
}

fn unix_timestamp_utc(year: i32, month: u32, day: u32, hour: u32, minute: u32, second: u32) -> i64 {
    let days = days_from_civil(year, month, day);
    days * 86_400 + hour as i64 * 3_600 + minute as i64 * 60 + second as i64
}

fn days_from_civil(year: i32, month: u32, day: u32) -> i64 {
    let adjusted_year = year - i32::from(month <= 2);
    let era = if adjusted_year >= 0 {
        adjusted_year / 400
    } else {
        (adjusted_year - 399) / 400
    };
    let year_of_era = adjusted_year - era * 400;
    let month_prime = month as i32 + if month > 2 { -3 } else { 9 };
    let day_of_year = (153 * month_prime + 2) / 5 + day as i32 - 1;
    let day_of_era = year_of_era * 365 + year_of_era / 4 - year_of_era / 100 + day_of_year;
    (era * 146_097 + day_of_era - 719_468) as i64
}

fn civil_from_days(days: i64) -> (i32, u32, u32) {
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let day_of_era = z - era * 146_097;
    let year_of_era =
        (day_of_era - day_of_era / 1_460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let mut year = year_of_era as i32 + (era as i32) * 400;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let month_prime = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * month_prime + 2) / 5 + 1;
    let month = month_prime + if month_prime < 10 { 3 } else { -9 };
    year += i32::from(month <= 2);
    (year, month as u32, day as u32)
}

fn current_unix_time() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .ok()
        .map(|duration| duration.as_secs() as i64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::HstsStore;

    #[test]
    fn hsts_prefers_exact_match_before_parent_tailmatch() {
        let mut store = HstsStore::default();
        store.remember("example.com", true, i64::MAX - 1);
        store.remember("a.example.com", true, i64::MAX);
        let match_entry = store.lookup("a.example.com").expect("hsts");
        assert_eq!(match_entry.host, "a.example.com");
    }

    #[test]
    fn hsts_prefers_longest_tailmatch() {
        let mut store = HstsStore::default();
        store.remember("example.com", true, i64::MAX - 1);
        store.remember("b.example.com", true, i64::MAX);
        let match_entry = store.lookup("c.b.example.com").expect("hsts");
        assert_eq!(match_entry.host, "b.example.com");
    }
}
