/*
 * Generated by safe/scripts/generate-manifests.py.
 * Transitional exhaustive forwarder bridge for the foundation phase.
 * This file must be removed in the final hardening phase.
 */
#define _GNU_SOURCE 1
#include <dlfcn.h>
#include <libgen.h>
#include <limits.h>
#include <pthread.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef REFERENCE_LIBRARY_FILE
#error "REFERENCE_LIBRARY_FILE must point at the sidecar reference library"
#endif

#ifndef BRIDGE_FLAVOR
#define BRIDGE_FLAVOR "unknown"
#endif

static pthread_once_t g_reference_once = PTHREAD_ONCE_INIT;
static void *g_reference_handle = NULL;

static void bridge_abort(const char *what, const char *detail) {
  fprintf(stderr, "libcurl transitional bridge (%s): %s: %s\n",
          BRIDGE_FLAVOR,
          what,
          detail ? detail : "(null)");
  abort();
}

static void bridge_open_reference(void) {
  Dl_info info;
  char self_path[PATH_MAX];
  char reference_path[PATH_MAX];
  const int flags = RTLD_NOW | RTLD_LOCAL;

  if(!dladdr((void *)&bridge_open_reference, &info) || !info.dli_fname)
    bridge_abort("dladdr", "could not resolve bridge location");

  if(snprintf(self_path, sizeof(self_path), "%s", info.dli_fname) <= 0)
    bridge_abort("snprintf", "failed to copy bridge path");

  if(snprintf(reference_path, sizeof(reference_path), "%s/%s",
              dirname(self_path),
              REFERENCE_LIBRARY_FILE) <= 0)
    bridge_abort("snprintf", "failed to compose reference path");

  g_reference_handle = dlopen(reference_path, flags);
  if(!g_reference_handle)
    bridge_abort("dlopen", dlerror());
}

static void *bridge_resolve_symbol(const char *name) {
  void *symbol = NULL;
  pthread_once(&g_reference_once, bridge_open_reference);
  symbol = dlsym(g_reference_handle, name);
  if(!symbol)
    bridge_abort("dlsym", name);
  return symbol;
}

#define DECLARE_FORWARDER(name) \
  static void *resolve_##name(void) { \
    return bridge_resolve_symbol(#name); \
  } \
  __attribute__((ifunc("resolve_" #name))) void name(void);

DECLARE_FORWARDER(curl_easy_cleanup)
DECLARE_FORWARDER(curl_easy_duphandle)
DECLARE_FORWARDER(curl_easy_escape)
DECLARE_FORWARDER(curl_easy_getinfo)
DECLARE_FORWARDER(curl_easy_header)
DECLARE_FORWARDER(curl_easy_init)
DECLARE_FORWARDER(curl_easy_nextheader)
DECLARE_FORWARDER(curl_easy_option_by_id)
DECLARE_FORWARDER(curl_easy_option_by_name)
DECLARE_FORWARDER(curl_easy_option_next)
DECLARE_FORWARDER(curl_easy_pause)
DECLARE_FORWARDER(curl_easy_perform)
DECLARE_FORWARDER(curl_easy_recv)
DECLARE_FORWARDER(curl_easy_reset)
DECLARE_FORWARDER(curl_easy_send)
DECLARE_FORWARDER(curl_easy_setopt)
DECLARE_FORWARDER(curl_easy_strerror)
DECLARE_FORWARDER(curl_easy_unescape)
DECLARE_FORWARDER(curl_easy_upkeep)
DECLARE_FORWARDER(curl_escape)
DECLARE_FORWARDER(curl_formadd)
DECLARE_FORWARDER(curl_formfree)
DECLARE_FORWARDER(curl_formget)
DECLARE_FORWARDER(curl_free)
DECLARE_FORWARDER(curl_getdate)
DECLARE_FORWARDER(curl_getenv)
DECLARE_FORWARDER(curl_global_cleanup)
DECLARE_FORWARDER(curl_global_init)
DECLARE_FORWARDER(curl_global_init_mem)
DECLARE_FORWARDER(curl_global_sslset)
DECLARE_FORWARDER(curl_global_trace)
DECLARE_FORWARDER(curl_maprintf)
DECLARE_FORWARDER(curl_mfprintf)
DECLARE_FORWARDER(curl_mime_addpart)
DECLARE_FORWARDER(curl_mime_data)
DECLARE_FORWARDER(curl_mime_data_cb)
DECLARE_FORWARDER(curl_mime_encoder)
DECLARE_FORWARDER(curl_mime_filedata)
DECLARE_FORWARDER(curl_mime_filename)
DECLARE_FORWARDER(curl_mime_free)
DECLARE_FORWARDER(curl_mime_headers)
DECLARE_FORWARDER(curl_mime_init)
DECLARE_FORWARDER(curl_mime_name)
DECLARE_FORWARDER(curl_mime_subparts)
DECLARE_FORWARDER(curl_mime_type)
DECLARE_FORWARDER(curl_mprintf)
DECLARE_FORWARDER(curl_msnprintf)
DECLARE_FORWARDER(curl_msprintf)
DECLARE_FORWARDER(curl_multi_add_handle)
DECLARE_FORWARDER(curl_multi_assign)
DECLARE_FORWARDER(curl_multi_cleanup)
DECLARE_FORWARDER(curl_multi_fdset)
DECLARE_FORWARDER(curl_multi_get_handles)
DECLARE_FORWARDER(curl_multi_info_read)
DECLARE_FORWARDER(curl_multi_init)
DECLARE_FORWARDER(curl_multi_perform)
DECLARE_FORWARDER(curl_multi_poll)
DECLARE_FORWARDER(curl_multi_remove_handle)
DECLARE_FORWARDER(curl_multi_setopt)
DECLARE_FORWARDER(curl_multi_socket)
DECLARE_FORWARDER(curl_multi_socket_action)
DECLARE_FORWARDER(curl_multi_socket_all)
DECLARE_FORWARDER(curl_multi_strerror)
DECLARE_FORWARDER(curl_multi_timeout)
DECLARE_FORWARDER(curl_multi_wait)
DECLARE_FORWARDER(curl_multi_wakeup)
DECLARE_FORWARDER(curl_mvaprintf)
DECLARE_FORWARDER(curl_mvfprintf)
DECLARE_FORWARDER(curl_mvprintf)
DECLARE_FORWARDER(curl_mvsnprintf)
DECLARE_FORWARDER(curl_mvsprintf)
DECLARE_FORWARDER(curl_pushheader_byname)
DECLARE_FORWARDER(curl_pushheader_bynum)
DECLARE_FORWARDER(curl_share_cleanup)
DECLARE_FORWARDER(curl_share_init)
DECLARE_FORWARDER(curl_share_setopt)
DECLARE_FORWARDER(curl_share_strerror)
DECLARE_FORWARDER(curl_slist_append)
DECLARE_FORWARDER(curl_slist_free_all)
DECLARE_FORWARDER(curl_strequal)
DECLARE_FORWARDER(curl_strnequal)
DECLARE_FORWARDER(curl_unescape)
DECLARE_FORWARDER(curl_url)
DECLARE_FORWARDER(curl_url_cleanup)
DECLARE_FORWARDER(curl_url_dup)
DECLARE_FORWARDER(curl_url_get)
DECLARE_FORWARDER(curl_url_set)
DECLARE_FORWARDER(curl_url_strerror)
DECLARE_FORWARDER(curl_version)
DECLARE_FORWARDER(curl_version_info)
DECLARE_FORWARDER(curl_ws_meta)
DECLARE_FORWARDER(curl_ws_recv)
DECLARE_FORWARDER(curl_ws_send)
