#! /bin/sh

prefix=/usr
exec_prefix=/usr
multiarch="@DEB_HOST_MULTIARCH@"
version="@CURLVERSION@"
vernum="080500"
ssl_backends="@SSL_BACKENDS@"
configure_args='--prefix=/usr --libdir=/usr/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH` --libexecdir=/usr/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH` --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` --disable-symbol-hiding --enable-versioned-symbols --enable-threaded-resolver @CONFIGURE_SSL_ARG@ --with-gssapi=/usr --with-nghttp2'

usage()
{
    cat <<EOF
Usage: curl-config [OPTION]

Available values for OPTION include:

  --built-shared says 'yes' if libcurl was built shared
  --ca        ca bundle install path
  --cc        compiler
  --cflags    pre-processor and compiler flags
  --checkfor [version] check for (lib)curl of the specified version
  --configure the arguments given to configure when building curl
  --features  newline separated list of enabled features
  --help      display this help and exit
  --libs      library linking information
  --prefix    curl install prefix
  --protocols newline separated list of enabled protocols
  --ssl-backends output the SSL backends libcurl was built to support
  --static-libs static libcurl library linking information
  --version   output version information
  --vernum    output the version information as a number (hexadecimal)
EOF
    exit "$1"
}

if test $# -eq 0; then
    usage 1
fi

while test $# -gt 0; do
    case "$1" in
    --built-shared)
        echo yes
        ;;
    --ca)
        echo /etc/ssl/certs/ca-certificates.crt
        ;;
    --cc)
        echo cc
        ;;
    --prefix)
        echo "$prefix"
        ;;
    --feature|--features)
        for feature in SSL IPv6 libz AsynchDNS IDN NTLM TLS-SRP HTTP2 UnixSockets PSL HSTS HTTPS-proxy alt-svc; do
            echo "$feature"
        done
        ;;
    --protocols)
        for protocol in DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS LDAP LDAPS MQTT POP3 POP3S RTMP RTSP SCP SFTP SMB SMBS SMTP SMTPS TELNET TFTP; do
            echo "$protocol"
        done
        ;;
    --version)
        echo "libcurl $version"
        ;;
    --checkfor)
        checkfor=$2
        cmajor=$(echo "$checkfor" | cut -d. -f1)
        cminor=$(echo "$checkfor" | cut -d. -f2)
        cpatch=$(echo "$checkfor" | cut -d. -f3 | cut -d- -f1)
        vmajor=$(echo "$version" | cut -d. -f1)
        vminor=$(echo "$version" | cut -d. -f2)
        vpatch=$(echo "$version" | cut -d. -f3 | cut -d- -f1)
        if test "$vmajor" -gt "$cmajor" ||
           { test "$vmajor" -eq "$cmajor" && test "$vminor" -gt "$cminor"; } ||
           { test "$vmajor" -eq "$cmajor" && test "$vminor" -eq "$cminor" && test "$cpatch" -le "$vpatch"; }; then
            exit 0
        fi
        echo "requested version $checkfor is newer than existing $version"
        exit 1
        ;;
    --vernum)
        echo "$vernum"
        ;;
    --help)
        usage 0
        ;;
    --cflags)
        echo "-I/usr/include/$multiarch"
        ;;
    --libs)
        echo "-L/usr/lib/$multiarch -lcurl"
        ;;
    --ssl-backends)
        echo "$ssl_backends"
        ;;
    --static-libs)
        echo "-Wl,-Bstatic -lcurl -Wl,-Bdynamic -lnghttp2 -lssh2 -lpsl -lz -ldl `krb5-config --libs gssapi`"
        ;;
    --configure)
        echo "$configure_args"
        ;;
    *)
        echo "unknown option: $1"
        usage 1
        ;;
    esac
    shift
done

exit 0
