#!/usr/bin/env python3
from __future__ import annotations

import argparse
import collections
import hashlib
import importlib.util
import json
import os
import pathlib
import re
import subprocess
from typing import Iterable


SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
DEFAULT_SAFE_DIR = SCRIPT_DIR.parent
DEFAULT_REPO_ROOT = DEFAULT_SAFE_DIR.parent
HEADER_DIR = DEFAULT_SAFE_DIR / "include" / "curl"

ASSIGNMENT_RE = re.compile(r"^([A-Za-z0-9_]+)\s*(\+?=)\s*(.*)$")
VAR_REF_RE = re.compile(r"\$\(([A-Za-z0-9_]+)\)")
BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.S)


def run_git(repo_root: pathlib.Path, *args: str) -> list[str]:
    result = subprocess.run(
        ["git", "-C", str(repo_root), *args],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return [line for line in result.stdout.splitlines() if line]


def sha256_path(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def normalize_whitespace(value: str) -> str:
    return " ".join(value.split())


def parse_symbols(symbols_path: pathlib.Path) -> dict:
    symbol_versions: list[dict] = []
    exports: list[str] = []
    namespace = None
    soname = None
    package = None
    for index, raw_line in enumerate(symbols_path.read_text().splitlines()):
        line = raw_line.strip()
        if not line:
            continue
        if index == 0:
            parts = line.split()
            soname, package = parts[0], parts[1]
            continue
        if line.startswith("*"):
            continue
        token, _, min_version = line.partition(" ")
        name, _, version = token.partition("@")
        if name == "HIDDEN":
            continue
        if name.startswith("CURL_") and name == version:
            namespace = name
            continue
        if name.startswith("curl_"):
            exports.append(name)
            symbol_versions.append(
                {
                    "symbol": name,
                    "namespace": version,
                    "first_version": min_version.strip(),
                }
            )
    return {
        "symbols_path": str(symbols_path.relative_to(DEFAULT_REPO_ROOT)),
        "package": package,
        "soname": soname,
        "namespace": namespace,
        "symbols": exports,
        "symbol_versions": symbol_versions,
    }


def render_version_script(symbol_manifest: dict) -> str:
    lines = [f"{symbol_manifest['namespace']} {{", "  global:"]
    for symbol in symbol_manifest["symbols"]:
        lines.append(f"    {symbol};")
    lines.extend(["  local:", "    *;", "};", ""])
    return "\n".join(lines)


def render_forwarders(symbols: list[str]) -> str:
    lines = [
        "/*",
        " * Generated by safe/scripts/generate-manifests.py.",
        " * Transitional exhaustive forwarder bridge for the foundation phase.",
        " * This file must be removed in the final hardening phase.",
        " */",
        "#define _GNU_SOURCE 1",
        "#include <dlfcn.h>",
        "#include <libgen.h>",
        "#include <limits.h>",
        "#include <pthread.h>",
        "#include <stdbool.h>",
        "#include <stdio.h>",
        "#include <stdlib.h>",
        "#include <string.h>",
        "",
        "#ifndef REFERENCE_LIBRARY_FILE",
        '#error "REFERENCE_LIBRARY_FILE must point at the sidecar reference library"',
        "#endif",
        "",
        "#ifndef BRIDGE_FLAVOR",
        '#define BRIDGE_FLAVOR "unknown"',
        "#endif",
        "",
        "static pthread_once_t g_reference_once = PTHREAD_ONCE_INIT;",
        "static void *g_reference_handle = NULL;",
        "",
        "static void bridge_abort(const char *what, const char *detail) {",
        '  fprintf(stderr, "libcurl transitional bridge (%s): %s: %s\\n",',
        "          BRIDGE_FLAVOR,",
        '          what,',
        '          detail ? detail : "(null)");',
        "  abort();",
        "}",
        "",
        "static void bridge_open_reference(void) {",
        "  Dl_info info;",
        "  char self_path[PATH_MAX];",
        "  char reference_path[PATH_MAX];",
        '  const int flags = RTLD_NOW | RTLD_LOCAL;',
        "",
        "  if(!dladdr((void *)&bridge_open_reference, &info) || !info.dli_fname)",
        '    bridge_abort("dladdr", "could not resolve bridge location");',
        "",
        '  if(snprintf(self_path, sizeof(self_path), "%s", info.dli_fname) <= 0)',
        '    bridge_abort("snprintf", "failed to copy bridge path");',
        "",
        '  if(snprintf(reference_path, sizeof(reference_path), "%s/%s",',
        "              dirname(self_path),",
        "              REFERENCE_LIBRARY_FILE) <= 0)",
        '    bridge_abort("snprintf", "failed to compose reference path");',
        "",
        "  g_reference_handle = dlopen(reference_path, flags);",
        "  if(!g_reference_handle)",
        '    bridge_abort("dlopen", dlerror());',
        "}",
        "",
        "static void *bridge_resolve_symbol(const char *name) {",
        "  void *symbol = NULL;",
        "  pthread_once(&g_reference_once, bridge_open_reference);",
        "  symbol = dlsym(g_reference_handle, name);",
        "  if(!symbol)",
        '    bridge_abort("dlsym", name);',
        "  return symbol;",
        "}",
        "",
        "#define DECLARE_FORWARDER(name) \\",
        "  static void *resolve_##name(void) { \\",
        "    return bridge_resolve_symbol(#name); \\",
        "  } \\",
        "  __attribute__((ifunc(\"resolve_\" #name))) void name(void);",
        "",
    ]
    for symbol in symbols:
        lines.append(f"DECLARE_FORWARDER({symbol})")
    lines.append("")
    return "\n".join(lines)


def parse_makefile(path: pathlib.Path) -> dict:
    raw_text = path.read_text()
    logical_lines: list[str] = []
    buffer = ""
    for raw_line in raw_text.splitlines():
        line = raw_line.rstrip()
        if not buffer and (not line.strip() or line.lstrip().startswith("#")):
            continue
        if buffer:
            buffer += " " + line.lstrip()
        else:
            buffer = line
        if buffer.endswith("\\"):
            buffer = buffer[:-1].rstrip()
            continue
        logical_lines.append(buffer.strip())
        buffer = ""

    variables: dict[str, str] = {}
    assignments: list[dict] = []
    for line in logical_lines:
        match = ASSIGNMENT_RE.match(line)
        if not match:
            continue
        name, operator, value = match.groups()
        value = value.strip()
        if operator == "+=" and name in variables:
            variables[name] = f"{variables[name]} {value}".strip()
        else:
            variables[name] = value
        assignments.append(
            {
                "name": name,
                "operator": operator,
                "value": value,
            }
        )

    return {
        "path": str(path.relative_to(DEFAULT_REPO_ROOT)),
        "raw_text": raw_text,
        "variables": variables,
        "assignments": assignments,
    }


def resolve_make_value(name: str, variables: dict[str, str], seen: set[str] | None = None) -> str:
    if seen is None:
        seen = set()
    if name in seen:
        return variables.get(name, "")
    seen = set(seen)
    seen.add(name)
    value = variables.get(name, "")

    def replace(match: re.Match[str]) -> str:
        ref_name = match.group(1)
        if ref_name in variables:
            return resolve_make_value(ref_name, variables, seen)
        return match.group(0)

    previous = None
    while previous != value:
        previous = value
        value = VAR_REF_RE.sub(replace, value)
    return normalize_whitespace(value)


def tokenize_make_value(value: str) -> list[str]:
    if not value:
        return []
    return [token for token in normalize_whitespace(value).split(" ") if token]


def strip_preprocessor_directives(text: str) -> str:
    kept_lines: list[str] = []
    skip_continuation = False
    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        if skip_continuation:
            skip_continuation = line.endswith("\\")
            continue
        if line.lstrip().startswith("#"):
            skip_continuation = line.endswith("\\")
            continue
        kept_lines.append(raw_line)
    return "\n".join(kept_lines)


def collect_function_declarations(header_dir: pathlib.Path) -> list[dict]:
    declarations: list[dict] = []
    for header_path in sorted(header_dir.glob("*.h")):
        text = strip_preprocessor_directives(BLOCK_COMMENT_RE.sub("", header_path.read_text()))
        current: list[str] = []
        for raw_line in text.splitlines():
            line = raw_line.strip()
            if not current:
                if "CURL_EXTERN" not in line:
                    continue
                current.append(line)
            else:
                if line:
                    current.append(line)
            if ";" not in line:
                continue
            declaration = normalize_whitespace(" ".join(current))
            declaration = declaration.split(";", 1)[0] + ";"
            if "(" in declaration and ")" in declaration:
                declarations.append(
                    {
                        "header": header_path.name,
                        "declaration": declaration,
                    }
                )
            current = []
    return declarations


def collect_struct_names(header_dir: pathlib.Path) -> list[str]:
    names: set[str] = set()
    patterns = [
        re.compile(r"typedef\s+struct\s+[A-Za-z0-9_]+\s+([A-Za-z0-9_]+)\s*;"),
        re.compile(r"typedef\s+struct\s+[A-Za-z0-9_]+\s*\{.*?\}\s*([A-Za-z0-9_]+)\s*;", re.S),
        re.compile(r"struct\s+([A-Za-z0-9_]+)\s*\{"),
        re.compile(r"struct\s+([A-Za-z0-9_]+)\s*;"),
    ]
    for header_path in sorted(header_dir.glob("*.h")):
        text = header_path.read_text()
        for pattern in patterns:
            for match in pattern.finditer(text):
                names.add(match.group(1))
    return sorted(names)


def parse_enum_blocks(text: str) -> list[tuple[str, str]]:
    pattern = re.compile(
        r"typedef\s+enum(?:\s+[A-Za-z0-9_]+)?\s*\{(.*?)\}\s*([A-Za-z0-9_]+)\s*;",
        re.S,
    )
    return [(body, name) for body, name in pattern.findall(text)]


def collect_enum_discriminants(header_dir: pathlib.Path) -> list[dict]:
    results: list[dict] = []
    for header_path in sorted(header_dir.glob("*.h")):
        text = BLOCK_COMMENT_RE.sub("", header_path.read_text())
        for body, enum_name in parse_enum_blocks(text):
            current_numeric = None
            for item in body.split(","):
                entry = item.strip()
                if not entry:
                    continue
                if "=" in entry:
                    name, expression = [part.strip() for part in entry.split("=", 1)]
                    resolved = None
                    try:
                        resolved = int(expression, 0)
                        current_numeric = resolved
                    except ValueError:
                        current_numeric = None
                    results.append(
                        {
                            "header": header_path.name,
                            "enum": enum_name,
                            "name": name,
                            "value_expression": expression,
                            "resolved_value": resolved,
                        }
                    )
                else:
                    if current_numeric is not None:
                        current_numeric += 1
                    results.append(
                        {
                            "header": header_path.name,
                            "enum": enum_name,
                            "name": entry,
                            "value_expression": None,
                            "resolved_value": current_numeric,
                        }
                    )
    return results


def collect_macro_aliases(header_dir: pathlib.Path) -> list[dict]:
    aliases: list[dict] = []
    for header_path in sorted(header_dir.glob("*.h")):
        for raw_line in header_path.read_text().splitlines():
            line = raw_line.strip()
            if not line.startswith("#define "):
                continue
            _, _, rest = line.partition(" ")
            name, _, value = rest.partition(" ")
            if "(" in name:
                continue
            if not re.match(r"^(CURL|CURLOT|CURLOPT|CURLINFO|CURLM|CURLSH|CURLU|LIBCURL)", name):
                continue
            value = value.strip()
            if not value:
                continue
            aliases.append(
                {
                    "header": header_path.name,
                    "name": name,
                    "value": value,
                    "is_alias": bool(re.search(r"[A-Za-z_][A-Za-z0-9_]*", value)),
                }
            )
    return aliases


def parse_version_info(curlver_path: pathlib.Path) -> dict:
    info: dict[str, str] = {}
    for raw_line in curlver_path.read_text().splitlines():
        if not raw_line.startswith("#define "):
            continue
        parts = raw_line.split(None, 2)
        if len(parts) == 3 and parts[1].startswith("LIBCURL_"):
            info[parts[1]] = parts[2]
    return info


def parse_easy_options(options_path: pathlib.Path, easyoptions_path: pathlib.Path) -> dict:
    options_text = options_path.read_text()
    easyoptions_text = easyoptions_path.read_text()
    entries: list[dict] = []
    for match in re.finditer(
        r'\{\s*"([^"]+)"\s*,\s*([A-Z0-9_]+)\s*,\s*([A-Z0-9_]+)\s*,\s*([A-Z0-9_|()<>+-]+)\s*\}',
        easyoptions_text,
        re.S,
    ):
        name, option_id, option_type, flags = match.groups()
        entries.append(
            {
                "name": name,
                "id": option_id,
                "type": option_type,
                "flags": flags,
                "is_alias": "CURLOT_FLAG_ALIAS" in flags,
            }
        )
    return {
        "options_header": str(options_path.relative_to(DEFAULT_REPO_ROOT)),
        "easyoptions_source": str(easyoptions_path.relative_to(DEFAULT_REPO_ROOT)),
        "easytypes": collect_enum_discriminants_from_text(options_text, "options.h"),
        "entries": entries,
    }


def collect_enum_discriminants_from_text(text: str, header_name: str) -> list[dict]:
    results: list[dict] = []
    clean = BLOCK_COMMENT_RE.sub("", text)
    for body, enum_name in parse_enum_blocks(clean):
        current_numeric = None
        for item in body.split(","):
            entry = item.strip()
            if not entry:
                continue
            if "=" in entry:
                name, expression = [part.strip() for part in entry.split("=", 1)]
                resolved = None
                try:
                    resolved = int(expression, 0)
                    current_numeric = resolved
                except ValueError:
                    current_numeric = None
                results.append(
                    {
                        "header": header_name,
                        "enum": enum_name,
                        "name": name,
                        "value_expression": expression,
                        "resolved_value": resolved,
                    }
                )
            else:
                if current_numeric is not None:
                    current_numeric += 1
                results.append(
                    {
                        "header": header_name,
                        "enum": enum_name,
                        "name": entry,
                        "value_expression": None,
                        "resolved_value": current_numeric,
                    }
                )
    return results


def load_json(path: pathlib.Path) -> dict:
    return json.loads(path.read_text())


def parse_disabled(disabled_path: pathlib.Path) -> dict:
    raw_text = disabled_path.read_text()
    entries: list[dict] = []
    per_test: dict[str, dict] = {}
    condition_stack: list[str] = []
    for line_number, raw_line in enumerate(raw_text.splitlines(), start=1):
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("%if "):
            condition_stack.append(stripped[4:].strip())
            continue
        if stripped == "%endif":
            if condition_stack:
                condition_stack.pop()
            continue
        if stripped == "%else":
            continue
        if stripped.isdigit():
            entry = {
                "line": line_number,
                "test_id": stripped,
                "conditions": list(condition_stack),
            }
            entries.append(entry)
            per_test.setdefault(
                stripped,
                {
                    "must_run_via_runtests_pl": True,
                    "conditional_blocks": [],
                    "selected_flavor_skip": {
                        "openssl": False,
                        "gnutls": False,
                    },
                    "discharged_elsewhere": [],
                },
            )
            if condition_stack:
                per_test[stripped]["conditional_blocks"].append(list(condition_stack))
            else:
                per_test[stripped]["selected_flavor_skip"]["openssl"] = True
                per_test[stripped]["selected_flavor_skip"]["gnutls"] = True
    return {
        "path": str(disabled_path.relative_to(DEFAULT_REPO_ROOT)),
        "raw_text": raw_text,
        "entries": entries,
        "per_test": per_test,
    }


def build_component_common(makefile_am: dict, makefile_inc: dict, extra_keys: Iterable[str] = ()) -> dict:
    merged = {**makefile_inc["variables"], **makefile_am["variables"]}
    keys = ["AM_CPPFLAGS", "AM_CFLAGS", "AM_LDFLAGS", "LDADD", "LIBS", *extra_keys]
    common = {}
    for key in keys:
        if key in merged:
            common[key] = {
                "raw": merged[key],
                "resolved": resolve_make_value(key, merged),
            }
    return common


def build_target_entry(
    component: str,
    target_name: str,
    merged_vars: dict[str, str],
    common: dict,
    role: str,
) -> dict:
    fields = {}
    for suffix in ["SOURCES", "CPPFLAGS", "CFLAGS", "LDFLAGS", "LDADD", "DEPENDENCIES"]:
        key = f"{target_name}_{suffix}"
        if key in merged_vars:
            fields[suffix.lower()] = {
                "raw": merged_vars[key],
                "resolved": resolve_make_value(key, merged_vars),
            }
    sources = tokenize_make_value(fields.get("sources", {}).get("resolved", ""))
    return {
        "target_id": f"{component}:{target_name}",
        "component": component,
        "name": target_name,
        "role": role,
        "common": common,
        "fields": fields,
        "sources": sources,
    }


def extract_rule(raw_text: str, rule_head: str) -> str | None:
    pattern = re.compile(rf"^{re.escape(rule_head)}:.*?(?=^\S|\Z)", re.M | re.S)
    match = pattern.search(raw_text)
    if not match:
        return None
    return match.group(0).rstrip()


def canonicalize_lib_path(component_root: pathlib.Path, token: str) -> pathlib.Path | None:
    if not token.endswith((".c", ".h", ".pl", ".pm", ".md", ".ini", ".in", ".rc")):
        return None
    candidate = (component_root / token).resolve()
    try:
        candidate.relative_to(DEFAULT_REPO_ROOT.resolve())
    except ValueError:
        return None
    return candidate


def collect_include_closure(initial_paths: Iterable[pathlib.Path], tracked: set[pathlib.Path]) -> set[pathlib.Path]:
    resolved = set(initial_paths)
    queue = collections.deque(initial_paths)
    include_re = re.compile(r'^\s*#\s*include\s+"([^"]+)"', re.M)
    while queue:
        path = queue.popleft()
        if not path.exists():
            continue
        text = path.read_text(errors="ignore")
        for include in include_re.findall(text):
            include_path = (path.parent / include).resolve()
            if include_path in tracked and include_path not in resolved:
                resolved.add(include_path)
                queue.append(include_path)
    return resolved


def build_test_manifest(repo_root: pathlib.Path, safe_dir: pathlib.Path) -> dict:
    data_makefile = parse_makefile(repo_root / "original/tests/data/Makefile.inc")
    libtest_makefile_inc = parse_makefile(repo_root / "original/tests/libtest/Makefile.inc")
    libtest_makefile_am = parse_makefile(repo_root / "original/tests/libtest/Makefile.am")
    server_makefile_inc = parse_makefile(repo_root / "original/tests/server/Makefile.inc")
    server_makefile_am = parse_makefile(repo_root / "original/tests/server/Makefile.am")
    http_makefile_inc = parse_makefile(repo_root / "original/tests/http/clients/Makefile.inc")
    http_makefile_am = parse_makefile(repo_root / "original/tests/http/clients/Makefile.am")
    src_makefile_inc = parse_makefile(repo_root / "original/src/Makefile.inc")
    src_makefile_am = parse_makefile(repo_root / "original/src/Makefile.am")
    unit_makefile_inc = parse_makefile(repo_root / "original/tests/unit/Makefile.inc")

    testcases = tokenize_make_value(resolve_make_value("TESTCASES", data_makefile["variables"]))
    testcase_duplicates = [
        token for token, count in collections.Counter(testcases).items() if count > 1
    ]
    disabled = parse_disabled(repo_root / "original/tests/data/DISABLED")
    on_disk_tests = [
        path.name
        for path in sorted((repo_root / "original/tests/data").glob("test*"))
        if path.is_file() and path.name.startswith("test")
    ]

    libtest_vars = {**libtest_makefile_inc["variables"], **libtest_makefile_am["variables"]}
    server_vars = {**server_makefile_inc["variables"], **server_makefile_am["variables"]}
    http_vars = {**http_makefile_inc["variables"], **http_makefile_am["variables"]}
    src_vars = {**src_makefile_inc["variables"], **src_makefile_am["variables"]}
    unit_vars = unit_makefile_inc["variables"]

    libtests = tokenize_make_value(resolve_make_value("noinst_PROGRAMS", libtest_vars))
    servers = tokenize_make_value(resolve_make_value("noinst_PROGRAMS", server_vars))
    http_clients = tokenize_make_value(resolve_make_value("check_PROGRAMS", http_vars))
    unit_source_ids = sorted(
        {
            assignment["name"].split("_", 1)[0]
            for assignment in unit_makefile_inc["assignments"]
            if assignment["name"].startswith("unit") and assignment["name"].endswith("_SOURCES")
        }
    )
    enabled_units = tokenize_make_value(resolve_make_value("UNITPROGS", unit_vars))

    libtest_common = build_component_common(
        libtest_makefile_am,
        libtest_makefile_inc,
        extra_keys=("SUPPORTFILES_LIBS", "TESTUTIL_LIBS"),
    )
    server_common = build_component_common(server_makefile_am, server_makefile_inc)
    http_common = build_component_common(http_makefile_am, http_makefile_inc, extra_keys=("LIBDIR",))
    src_common = build_component_common(src_makefile_am, src_makefile_inc)

    targets: list[dict] = []
    targets.append(build_target_entry("src", "curl", src_vars, src_common, "curl-tool"))
    for name in libtests:
        role = "helper" if name == "chkhostname" else "libcurl-consumer"
        targets.append(build_target_entry("libtest", name, libtest_vars, libtest_common, role))
    for name in servers:
        targets.append(build_target_entry("server", name, server_vars, server_common, "helper"))
    for name in http_clients:
        target = build_target_entry("http-client", name.replace("-", "_"), http_vars, http_common, "libcurl-consumer")
        if not target["sources"]:
            target["sources"] = [f"{name}.c"]
        target["name"] = name
        target["target_id"] = f"http-client:{name}"
        targets.append(target)

    generated_rules = [
        {
            "name": "tool_hugehelp.c",
            "source": "original/src/Makefile.am",
            "rule": extract_rule(src_makefile_am["raw_text"], "$(HUGE)"),
        },
        {
            "name": "lib1521.c",
            "source": "original/tests/libtest/Makefile.am",
            "rule": extract_rule(libtest_makefile_am["raw_text"], "lib1521.c"),
        },
    ]
    shared_source_variants = [
        {"source": "lib526.c", "targets": ["lib526", "lib527", "lib532"]},
        {"source": "lib544.c", "targets": ["lib544", "lib545"]},
        {"source": "lib547.c", "targets": ["lib547", "lib548"]},
        {"source": "lib670.c", "targets": ["lib670", "lib671", "lib672", "lib673"]},
        {"source": "lib525.c", "targets": ["lib525", "lib529"]},
        {"source": "lib510.c", "targets": ["lib510", "lib565"]},
    ]

    tracked_vendor_paths = {
        (repo_root / relative).resolve()
        for relative in run_git(
            repo_root,
            "ls-files",
            "--",
            "original/src",
            "original/tests",
            "original/.pc/90_gnutls.patch",
            "original/debian/tests/LDAP-bindata.c",
        )
    }
    direct_lib_refs: set[pathlib.Path] = set()
    component_roots = {
        "src": repo_root / "original/src",
        "libtest": repo_root / "original/tests/libtest",
        "server": repo_root / "original/tests/server",
        "http-client": repo_root / "original/tests/http/clients",
    }
    for target in targets:
        root = component_roots[target["component"]]
        for source in target["sources"]:
            candidate = canonicalize_lib_path(root, source)
            if candidate and "/original/lib/" in str(candidate):
                direct_lib_refs.add(candidate)

    for key in ["CURLX_CFILES", "CURLX_HFILES", "CURLTOOL_LIBCURL_CFILES"]:
        if key in src_vars:
            for token in tokenize_make_value(resolve_make_value(key, src_vars)):
                candidate = canonicalize_lib_path(repo_root / "original/src", token)
                if candidate:
                    direct_lib_refs.add(candidate)
    for key in ["CURLX_SRCS", "CURLX_HDRS", "USEFUL", "UTIL"]:
        if key in server_vars:
            for token in tokenize_make_value(resolve_make_value(key, server_vars)):
                candidate = canonicalize_lib_path(repo_root / "original/tests/server", token)
                if candidate and "/original/lib/" in str(candidate):
                    direct_lib_refs.add(candidate)
    for target in targets:
        root = component_roots[target["component"]]
        for source in target["sources"]:
            candidate = canonicalize_lib_path(root, source)
            if candidate:
                direct_lib_refs.add(candidate)

    tracked_lib_paths = {
        path
        for path in tracked_vendor_paths
        if "/original/lib/" in str(path)
    }
    include_closure = collect_include_closure(direct_lib_refs, tracked_lib_paths)
    vendor_entries = []
    for path in sorted(tracked_vendor_paths | include_closure):
        relative = path.relative_to(repo_root)
        vendor_entries.append(
            {
                "source": str(relative),
                "destination": f"safe/vendor/upstream/{relative.as_posix()[len('original/') :]}",
                "tracked": True,
                "sha256": sha256_path(path),
            }
        )

    dependents = load_json(repo_root / "dependents.json")
    autopkgtests = run_git(repo_root, "ls-files", "--", "original/debian/tests")

    return {
        "schema_version": 1,
        "generated_at": os.environ.get("SOURCE_DATE_EPOCH", "deterministic-build"),
        "raw_ordered_testcases": testcases,
        "duplicate_testcase_tokens": testcase_duplicates,
        "disabled": disabled,
        "canonical_test_files": on_disk_tests,
        "libtests": {
            "programs": libtests,
            "count": len(libtests),
        },
        "units": {
            "source_ids": unit_source_ids,
            "count": len(unit_source_ids),
            "enabled_subset": enabled_units,
        },
        "http_clients": {
            "programs": http_clients,
            "count": len(http_clients),
        },
        "server_helpers": {
            "programs": servers,
            "count": len(servers),
        },
        "curl_tool_sources": {
            "curl_cfiles": tokenize_make_value(resolve_make_value("CURL_CFILES", src_vars)),
            "curlx_cfiles": tokenize_make_value(resolve_make_value("CURLX_CFILES", src_vars)),
            "curl_hfiles": tokenize_make_value(resolve_make_value("CURL_HFILES", src_vars)),
            "curl_rcfiles": tokenize_make_value(resolve_make_value("CURL_RCFILES", src_vars)),
        },
        "compatibility_build": {
            "build_files": [
                libtest_makefile_am["path"],
                libtest_makefile_inc["path"],
                server_makefile_am["path"],
                server_makefile_inc["path"],
                http_makefile_am["path"],
                http_makefile_inc["path"],
                src_makefile_am["path"],
                src_makefile_inc["path"],
            ],
            "common": {
                "src": src_common,
                "libtest": libtest_common,
                "server": server_common,
                "http-client": http_common,
            },
            "targets": sorted(targets, key=lambda item: item["target_id"]),
            "generated_source_rules": generated_rules,
            "shared_source_variants": shared_source_variants,
        },
        "vendor_inventory": {
            "root": "safe/vendor/upstream",
            "entries": vendor_entries,
        },
        "debian_tests": {
            "scripts": autopkgtests,
            "dependent_names": [entry["name"] for entry in dependents["dependents"]],
        },
        "notes": [
            "original/tests/http/README.md references pytest assets that are not present in the tracked workspace."
        ],
    }


def build_abi_manifest(repo_root: pathlib.Path, safe_dir: pathlib.Path) -> dict:
    openssl_symbols = parse_symbols(repo_root / "original/debian/libcurl4t64.symbols")
    gnutls_symbols = parse_symbols(repo_root / "original/debian/libcurl3t64-gnutls.symbols")
    header_hashes = {
        path.name: sha256_path(path)
        for path in sorted((safe_dir / "include" / "curl").glob("*.h"))
    }
    return {
        "schema_version": 1,
        "version_strings": parse_version_info(repo_root / "original/include/curl/curlver.h"),
        "shared_libraries": {
            "openssl": {
                "filename": openssl_symbols["soname"],
                "soname": openssl_symbols["soname"],
                "namespace": openssl_symbols["namespace"],
            },
            "gnutls": {
                "filename": gnutls_symbols["soname"],
                "soname": gnutls_symbols["soname"],
                "namespace": gnutls_symbols["namespace"],
            },
        },
        "symbols": {
            "openssl": openssl_symbols["symbol_versions"],
            "gnutls": gnutls_symbols["symbol_versions"],
        },
        "header_hashes": header_hashes,
        "public_function_declarations": collect_function_declarations(safe_dir / "include" / "curl"),
        "public_struct_names": collect_struct_names(safe_dir / "include" / "curl"),
        "public_enum_discriminants": collect_enum_discriminants(safe_dir / "include" / "curl"),
        "public_macro_aliases": collect_macro_aliases(safe_dir / "include" / "curl"),
        "option_metadata": parse_easy_options(
            repo_root / "original/include/curl/options.h",
            repo_root / "original/lib/easyoptions.c",
        ),
    }


def build_cve_manifest(repo_root: pathlib.Path) -> dict:
    curated = load_json(repo_root / "relevant_cves.json")
    curated_ids = {entry["cve_id"] for entry in curated["cves"]}
    patch_mappings = []
    for patch_path in sorted((repo_root / "original/debian/patches").glob("CVE-*.patch")):
        stem = patch_path.stem
        cve_id = stem
        suffix_match = re.match(r"^(CVE-\d{4}-\d+)(?:-(?:pre\d+|\d+))$", stem)
        if cve_id not in curated_ids and suffix_match:
            cve_id = suffix_match.group(1)
        patch_mappings.append(
            {
                "patch": str(patch_path.relative_to(repo_root)),
                "mapped_cve_id": cve_id,
                "match_found": cve_id in curated_ids,
            }
        )
    return {
        "schema_version": 1,
        "curated_relevant_cves": curated,
        "debian_patch_mappings": patch_mappings,
    }


def write_json(path: pathlib.Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


def write_outputs(safe_dir: pathlib.Path, output_root: pathlib.Path) -> None:
    repo_root = safe_dir.parent
    abi_manifest = build_abi_manifest(repo_root, safe_dir)
    test_manifest = build_test_manifest(repo_root, safe_dir)
    cve_manifest = build_cve_manifest(repo_root)

    write_json(output_root / "metadata/abi-manifest.json", abi_manifest)
    write_json(output_root / "metadata/test-manifest.json", test_manifest)
    write_json(output_root / "metadata/cve-manifest.json", cve_manifest)

    openssl_symbols = parse_symbols(repo_root / "original/debian/libcurl4t64.symbols")
    gnutls_symbols = parse_symbols(repo_root / "original/debian/libcurl3t64-gnutls.symbols")
    (output_root / "abi").mkdir(parents=True, exist_ok=True)
    (output_root / "abi/libcurl-openssl.map").write_text(render_version_script(openssl_symbols))
    (output_root / "abi/libcurl-gnutls.map").write_text(render_version_script(gnutls_symbols))
    (output_root / "c_shim").mkdir(parents=True, exist_ok=True)
    (output_root / "c_shim/forwarders.c").write_text(render_forwarders(openssl_symbols["symbols"]))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--safe-dir", default=str(DEFAULT_SAFE_DIR))
    parser.add_argument("--output-root", default=None)
    args = parser.parse_args()

    safe_dir = pathlib.Path(args.safe_dir).resolve()
    output_root = pathlib.Path(args.output_root).resolve() if args.output_root else safe_dir
    write_outputs(safe_dir, output_root)


if __name__ == "__main__":
    main()
