#!/usr/bin/env python3
from __future__ import annotations

import argparse
import pathlib
import re


SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
DEFAULT_SAFE_DIR = SCRIPT_DIR.parent


def collect_struct_names(header_dir: pathlib.Path) -> list[str]:
    patterns = [
        re.compile(r"typedef\s+struct\s+[A-Za-z0-9_]+\s+([A-Za-z0-9_]+)\s*;"),
        re.compile(r"typedef\s+struct\s+[A-Za-z0-9_]+\s*\{.*?\}\s*([A-Za-z0-9_]+)\s*;", re.S),
        re.compile(r"struct\s+([A-Za-z0-9_]+)\s*\{"),
        re.compile(r"struct\s+([A-Za-z0-9_]+)\s*;"),
    ]
    names: set[str] = set()
    for header_path in sorted(header_dir.glob("*.h")):
        text = header_path.read_text()
        for pattern in patterns:
            for match in pattern.finditer(text):
                names.add(match.group(1))
    return sorted(names)


def render(safe_dir: pathlib.Path) -> str:
    struct_names = collect_struct_names(safe_dir / "include" / "curl")
    arch_definitions = [
        ("x86_64", "linux_amd64", "core::ffi::c_long", "u32"),
        ("aarch64", "linux_arm64", "core::ffi::c_long", "u32"),
        ("arm", "linux_armhf", "core::ffi::c_longlong", "u32"),
        ("x86", "linux_i386", "core::ffi::c_longlong", "u32"),
        ("powerpc64", "linux_ppc64el", "core::ffi::c_long", "u32"),
        ("riscv64", "linux_riscv64", "core::ffi::c_long", "u32"),
        ("s390x", "linux_s390x", "core::ffi::c_long", "u32"),
    ]
    lines = [
        "// Generated by safe/scripts/generate-bindings.py.",
        "// Foundation-phase scaffold only: exact public field layouts land in impl-public-abi.",
        "",
        "use core::ffi::{c_char, c_int, c_long, c_void};",
        "",
        "pub mod arch {",
    ]
    for target_arch, module_name, curl_off_t, curl_socklen_t in arch_definitions:
        lines.extend(
            [
                f"    #[cfg(target_arch = \"{target_arch}\")]",
                f"    pub mod {module_name} {{",
                f"        pub type curl_off_t = {curl_off_t};",
                f"        pub type curl_socklen_t = {curl_socklen_t};",
                "    }",
                "",
            ]
        )
    lines.extend(
        [
            "    #[cfg(not(any(",
            "        target_arch = \"x86_64\",",
            "        target_arch = \"aarch64\",",
            "        target_arch = \"arm\",",
            "        target_arch = \"x86\",",
            "        target_arch = \"powerpc64\",",
            "        target_arch = \"riscv64\",",
            "        target_arch = \"s390x\"",
            "    )))]",
            "    pub mod generic {",
            "        pub type curl_off_t = core::ffi::c_longlong;",
            "        pub type curl_socklen_t = u32;",
            "    }",
            "}",
            "",
        ]
    )
    for target_arch, module_name, _, _ in arch_definitions:
        lines.extend(
            [
                f"#[cfg(target_arch = \"{target_arch}\")]",
                f"pub use arch::{module_name}::*;",
            ]
        )
    lines.extend(
        [
            "#[cfg(not(any(",
            "    target_arch = \"x86_64\",",
            "    target_arch = \"aarch64\",",
            "    target_arch = \"arm\",",
            "    target_arch = \"x86\",",
            "    target_arch = \"powerpc64\",",
            "    target_arch = \"riscv64\",",
            "    target_arch = \"s390x\"",
            ")))]",
            "pub use arch::generic::*;",
            "",
            "pub type size_t = usize;",
            "pub type time_t = c_long;",
            "",
            "#[repr(C)]",
            "pub struct curl_opaque_placeholder {",
            "    _private: [u8; 0],",
            "}",
            "",
        ]
    )
    for name in struct_names:
        lines.extend(
            [
                "#[repr(C)]",
                f"pub struct {name} {{",
                "    _private: [u8; 0],",
                "}",
                "",
            ]
        )
    lines.extend(
        [
            "pub type curl_malloc_callback = Option<unsafe extern \"C\" fn(size_t) -> *mut c_void>;",
            "pub type curl_free_callback = Option<unsafe extern \"C\" fn(*mut c_void)>;",
            "pub type curl_realloc_callback = Option<unsafe extern \"C\" fn(*mut c_void, size_t) -> *mut c_void>;",
            "pub type curl_calloc_callback = Option<unsafe extern \"C\" fn(size_t, size_t) -> *mut c_void>;",
            "pub type curl_read_callback = Option<unsafe extern \"C\" fn(*mut c_char, size_t, size_t, *mut c_void) -> size_t>;",
            "pub type curl_write_callback = Option<unsafe extern \"C\" fn(*mut c_char, size_t, size_t, *mut c_void) -> size_t>;",
            "pub type curl_ioctl_callback = Option<unsafe extern \"C\" fn(*mut CURL, c_int, *mut c_void) -> c_int>;",
            "pub type curl_socklen_t_alias = curl_socklen_t;",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--safe-dir", default=str(DEFAULT_SAFE_DIR))
    parser.add_argument("--output", default=None)
    args = parser.parse_args()

    safe_dir = pathlib.Path(args.safe_dir).resolve()
    output_path = pathlib.Path(args.output).resolve() if args.output else safe_dir / "src/abi/generated.rs"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render(safe_dir))


if __name__ == "__main__":
    main()
