// Generated by safe/scripts/generate-bindings.py.
// Foundation-phase scaffold only: exact public field layouts land in impl-public-abi.

use core::ffi::{c_char, c_int, c_long, c_void};

pub mod arch {
    #[cfg(target_arch = "x86_64")]
    pub mod linux_amd64 {
        pub type curl_off_t = core::ffi::c_long;
        pub type curl_socklen_t = u32;
    }

    #[cfg(target_arch = "aarch64")]
    pub mod linux_arm64 {
        pub type curl_off_t = core::ffi::c_long;
        pub type curl_socklen_t = u32;
    }

    #[cfg(target_arch = "arm")]
    pub mod linux_armhf {
        pub type curl_off_t = core::ffi::c_longlong;
        pub type curl_socklen_t = u32;
    }

    #[cfg(target_arch = "x86")]
    pub mod linux_i386 {
        pub type curl_off_t = core::ffi::c_longlong;
        pub type curl_socklen_t = u32;
    }

    #[cfg(target_arch = "powerpc64")]
    pub mod linux_ppc64el {
        pub type curl_off_t = core::ffi::c_long;
        pub type curl_socklen_t = u32;
    }

    #[cfg(target_arch = "riscv64")]
    pub mod linux_riscv64 {
        pub type curl_off_t = core::ffi::c_long;
        pub type curl_socklen_t = u32;
    }

    #[cfg(target_arch = "s390x")]
    pub mod linux_s390x {
        pub type curl_off_t = core::ffi::c_long;
        pub type curl_socklen_t = u32;
    }

    #[cfg(not(any(
        target_arch = "x86_64",
        target_arch = "aarch64",
        target_arch = "arm",
        target_arch = "x86",
        target_arch = "powerpc64",
        target_arch = "riscv64",
        target_arch = "s390x"
    )))]
    pub mod generic {
        pub type curl_off_t = core::ffi::c_longlong;
        pub type curl_socklen_t = u32;
    }
}

#[cfg(target_arch = "x86_64")]
pub use arch::linux_amd64::*;
#[cfg(target_arch = "aarch64")]
pub use arch::linux_arm64::*;
#[cfg(target_arch = "arm")]
pub use arch::linux_armhf::*;
#[cfg(target_arch = "x86")]
pub use arch::linux_i386::*;
#[cfg(target_arch = "powerpc64")]
pub use arch::linux_ppc64el::*;
#[cfg(target_arch = "riscv64")]
pub use arch::linux_riscv64::*;
#[cfg(target_arch = "s390x")]
pub use arch::linux_s390x::*;
#[cfg(not(any(
    target_arch = "x86_64",
    target_arch = "aarch64",
    target_arch = "arm",
    target_arch = "x86",
    target_arch = "powerpc64",
    target_arch = "riscv64",
    target_arch = "s390x"
)))]
pub use arch::generic::*;

pub type size_t = usize;
pub type time_t = c_long;

#[repr(C)]
pub struct curl_opaque_placeholder {
    _private: [u8; 0],
}

#[repr(C)]
pub struct CURL {
    _private: [u8; 0],
}

#[repr(C)]
pub struct CURLM {
    _private: [u8; 0],
}

#[repr(C)]
pub struct CURLMsg {
    _private: [u8; 0],
}

#[repr(C)]
pub struct CURLSH {
    _private: [u8; 0],
}

#[repr(C)]
pub struct CURLU {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_blob {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_certinfo {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_easyoption {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_fileinfo {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_forms {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_header {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_hstsentry {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_httppost {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_index {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_khkey {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_mime {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_mimepart {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_pushheaders {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_slist {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_sockaddr {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_ssl_backend {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_tlssessioninfo {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_version_info_data {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_waitfd {
    _private: [u8; 0],
}

#[repr(C)]
pub struct curl_ws_frame {
    _private: [u8; 0],
}

pub type curl_malloc_callback = Option<unsafe extern "C" fn(size_t) -> *mut c_void>;
pub type curl_free_callback = Option<unsafe extern "C" fn(*mut c_void)>;
pub type curl_realloc_callback = Option<unsafe extern "C" fn(*mut c_void, size_t) -> *mut c_void>;
pub type curl_calloc_callback = Option<unsafe extern "C" fn(size_t, size_t) -> *mut c_void>;
pub type curl_read_callback = Option<unsafe extern "C" fn(*mut c_char, size_t, size_t, *mut c_void) -> size_t>;
pub type curl_write_callback = Option<unsafe extern "C" fn(*mut c_char, size_t, size_t, *mut c_void) -> size_t>;
pub type curl_ioctl_callback = Option<unsafe extern "C" fn(*mut CURL, c_int, *mut c_void) -> c_int>;
pub type curl_socklen_t_alias = curl_socklen_t;
