// Generated by safe/scripts/generate-bindings.py and extended in impl-public-abi.

use core::ffi::{c_char, c_int, c_long, c_uint, c_void};

pub mod arch {
    #[cfg(target_arch = "x86_64")]
    pub mod linux_amd64 {
        pub type curl_off_t = core::ffi::c_long;
        pub type curl_socklen_t = u32;
    }

    #[cfg(target_arch = "aarch64")]
    pub mod linux_arm64 {
        pub type curl_off_t = core::ffi::c_long;
        pub type curl_socklen_t = u32;
    }

    #[cfg(target_arch = "arm")]
    pub mod linux_armhf {
        pub type curl_off_t = core::ffi::c_longlong;
        pub type curl_socklen_t = u32;
    }

    #[cfg(target_arch = "x86")]
    pub mod linux_i386 {
        pub type curl_off_t = core::ffi::c_longlong;
        pub type curl_socklen_t = u32;
    }

    #[cfg(target_arch = "powerpc64")]
    pub mod linux_ppc64el {
        pub type curl_off_t = core::ffi::c_long;
        pub type curl_socklen_t = u32;
    }

    #[cfg(target_arch = "riscv64")]
    pub mod linux_riscv64 {
        pub type curl_off_t = core::ffi::c_long;
        pub type curl_socklen_t = u32;
    }

    #[cfg(target_arch = "s390x")]
    pub mod linux_s390x {
        pub type curl_off_t = core::ffi::c_long;
        pub type curl_socklen_t = u32;
    }

    #[cfg(not(any(
        target_arch = "x86_64",
        target_arch = "aarch64",
        target_arch = "arm",
        target_arch = "x86",
        target_arch = "powerpc64",
        target_arch = "riscv64",
        target_arch = "s390x"
    )))]
    pub mod generic {
        pub type curl_off_t = core::ffi::c_longlong;
        pub type curl_socklen_t = u32;
    }
}

#[cfg(target_arch = "x86_64")]
pub use arch::linux_amd64::*;
#[cfg(target_arch = "aarch64")]
pub use arch::linux_arm64::*;
#[cfg(target_arch = "arm")]
pub use arch::linux_armhf::*;
#[cfg(target_arch = "x86")]
pub use arch::linux_i386::*;
#[cfg(target_arch = "powerpc64")]
pub use arch::linux_ppc64el::*;
#[cfg(target_arch = "riscv64")]
pub use arch::linux_riscv64::*;
#[cfg(target_arch = "s390x")]
pub use arch::linux_s390x::*;
#[cfg(not(any(
    target_arch = "x86_64",
    target_arch = "aarch64",
    target_arch = "arm",
    target_arch = "x86",
    target_arch = "powerpc64",
    target_arch = "riscv64",
    target_arch = "s390x"
)))]
pub use arch::generic::*;

include!("public_types.rs");
